config/routes.rb
Rails.application.routes.draw do
  get 'currency/index'

  get 'message/index'

  get 'message/test'

  get 'signup/index'

  get 'calculator/index'

  post 'qrcode/index'

  get 'qrcode/show'

  post 'signup/show'

  get 'address/show'

  post 'address/index'

  get 'sessions/index' 

  post 'sessions/show'

  root to: 'sessions#index'

  get "message/success"

  get "message/error"
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      controller :whatever, path: '/currency/index' do
        match 'post_action', via: [ :post, :options]
      end
    end
  end 

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      controller :whatever, path: '/message/index' do
        match 'post_action', via: [ :post, :options ]
      end
    end
  end 

end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  def show
    
  end

  def index
  	user = params[:account]
    pass = params[:password]
    @addresses=''
    personal_wallet = Blockchain::Wallet.new(user,pass,'d469606f-9967-4b10-a695-1765039c010a')
    begin
		@addresses = personal_wallet.list_addresses()
	rescue
    	redirect_to root_path, notice: "Account or password is wrong!"
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def index
  	@ticker = Blockchain::get_ticker()
  	@address = params[:address]
  	@balance = (params[:balance].to_f/(10**8)).to_f
  end
end

app/controllers/currency_controller.rb
class CurrencyController < ApplicationController
    skip_before_filter :verify_authenticity_token
    before_filter :cors_preflight_check
    after_filter :cors_set_access_control_headers
	def index

	  	@ticker = Blockchain::get_ticker()
	  	respond_to do |format|
	  		format.html { render :index }
	  		format.js { render :layout => false}
	  		format.json { render json: @ticker }  	
	  	end
	end

    def cors_set_access_control_headers
		headers['Access-Control-Allow-Origin'] = '*'
		headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
		headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
		headers['Access-Control-Max-Age'] = "1728000"
	end
 
	def cors_preflight_check
		if request.method == 'OPTIONS'
			headers['Access-Control-Allow-Origin'] = '*'
			headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
			headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
			headers['Access-Control-Max-Age'] = '1728000'
			 
			render :text => '', :content_type => 'text/plain'
		end
	end 
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers
  def index 
  	@money = params[:money]
    receive = params[:address]
  	address = Blockchain::get_address(receive)
  	@output = address.transactions[0].outputs[0].value
  	if @output ==  @money.to_f*(10**8)
      res = {"status" => "success"}
      respond_to do |format|
        format.html { render :index }
        format.js { render :layout => false}
        format.json { render json: res }    
      end
  	else
      res = {"status" => "error"}
      respond_to do |format|
        format.html { render :index }
        format.js { render :layout => false}
        format.json { render json: res }    
      end
  	end

  end

  def test
    address = Blockchain::get_address('1E3z7bn4ZeBa47GBBBSfWBFyw1TrXYonxS')
    @out = address.transactions[0].outputs
    @in = address.transactions[0].inputs
  end

  def success
  end

  def error
  end

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end
 
  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'
       
      render :text => '', :content_type => 'text/plain'
    end
  end 

end

app/controllers/qrcode_controller.rb
class QrcodeController < ApplicationController
  def index
  	@currency = params[:currency]
  	ticker = Blockchain::get_ticker()
  	ticker.keys.each do |key| 
  		if key == @currency
  			@rate=ticker[key].p15min
  		end
  	end
  	@address=params[:address]
  	@amount=params[:display]
  	@bitcoin=Blockchain::to_btc(@currency, @amount)
    url='bitcoin:'+ @address +'?amount=' + @bitcoin.to_s
    @qr = RQRCode::QRCode.new(url, :size => 4, :level => 'l'.to_sym) 
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  	if params[:account]!= nil 
  		redirect_to address_index_path
  	end
  end

  def show
  	@account = params[:account]
  	@password = params[:password]
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  	
  end
  def show
  	@password=params[:password]
  	@confirm_password=params[:confirm_password]
  	@email=params[:email]
  	if @password==@confirm_password
  		@wallet = Blockchain::create_wallet(@password, 'd469606f-9967-4b10-a695-1765039c010a', email:@email)
  	end
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/address/index.html.erb
<% if @addresses!=''%>
	<h1>Please Choose Your Address</h1>
	<% @addresses.each do |w| %>
		<%= "Address: " + w.address.to_s + " Balance: " + (w.balance.to_f/(10**8)).to_s %>
		<%= link_to "choose", calculator_index_url(address: w.address, balance: w.balance) %>
		<br />
		<br />
	<% end %>
<% end %>

app/views/calculator/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script language = "javascript">

	$(document).ready(function(){
  
		var curShow = "";
		var exp = "";
		var restartFlag = false;
		$("#display").val(curShow);

		$(".numBtn").click(function(){
			if($("#clearBtn").val() == "ac")
			{
				$("#clearBtn").val("c");
				$("#clearBtn").html("C");
			}
			if( restartFlag == true)
			{
				exp = "";
				curShow = "";
				restartFlag = false;
			}

			if($(this).val() == "." && curShow == "")
			{
				curShow = "0.";
			}
			else if($(this).val() == "." && isDotExist(curShow ))
			{
				return;
			}
			else if($(this).val() == "0" && ( curShow == "0") )
			{
				return;
			}
			else
			{
				curShow += $(this).val();
			}
			$("#display").val(curShow);
		});

		$(".opBtn").click(function(){
			exp += curShow;
			if(exp == "")
			{
				alert("Please input a number");
				return;
			}
			op = $(this).val();			
			restartFlag = false;

			if(isLastOp(exp))
			{
				if(op != "=")
				{
					exp = exp.substring(0 , exp.length - 1);
					exp += op;
				}
				else
				{
					$("#display").val(exp.substring(0 , exp.length - 1));
				}
			}
			else
			{
				res = eval(exp);
				$("#display").val(res);
				exp = res.toString();
				if(op != "=")
				{
					exp += op;
				}
				else
				{
					restartFlag = true;
					$("#clearBtn").val("ac");
					$("#clearBtn").html("AC");
				}
			}

			curShow = "";
		});

		$("#clearBtn").click(function(){
			if($(this).val() == "c")
			{
				curShow = "";
				$(this).val("ac");
				$(this).html("AC");
			}
			else
			{
				curShow = "";
				exp = "";
			}
			$("#display").val(curShow);
		});
	});

	$("#submit").click(function(){
		if($("#display").val() == "" )
		{
			$("#display").val("0");
		}
	});

	function isDotExist(string)
	{
		for(var i = 0; i <= string.length - 1 ; i++)
		{
			if(string[i] == ".")
			{
				return true;
			}
		}
		return false;
	}

	function isLastOp(string)
	{
		lastItem = string[string.length - 1];
		if(lastItem == "+")
			return true;
		else if(lastItem == "-")
			return true;
		else if(lastItem == "*")
			return true;
		else if(lastItem == "/")
			return true;
		else
			return false;
	}

	function isLastDot(string)
	{
		lastItem = string[string.length - 1];
		if(lastItem == ".")
			return true;
		else 
			return false;
	}
</script>

<h1>Your address</h1>
<p><%= @address %></p>
<h1>Your balance</h1>
<p><%= @balance.to_s+'BTC'%></p>
<%= form_tag "/qrcode/index/" , :method => "post" do %>
<br/>
<%= text_field_tag "address" , @address , :type => :hidden %>
<%= text_field_tag "display" , "" , :readonly => true%>
<%= select_tag "currency", options_for_select(@ticker.keys,"AUD")%>
<%= submit_tag "OK" , :id => :submit %>
<% end %>
<br/>
<br/>
<button id = "button1" value = "1" class = "numBtn">1</button>
<button id = "button2" value = "2" class = "numBtn">2</button>
<button id = "button3" value = "3" class = "numBtn">3</button>
<button id = "addBtn" value = "+" class = "opBtn">+</button>
<br/>
<br/>
<button id = "button4" value = "4" class = "numBtn">4</button>
<button id = "button5" value = "5" class = "numBtn">5</button>
<button id = "button6" value = "6" class = "numBtn">6</button>
<button id = "subBtn" value = "-" class = "opBtn">-</button>
<br/>
<br/>
<button id = "button7" value = "7" class = "numBtn">7</button>
<button id = "button8" value = "8" class = "numBtn">8</button>
<button id = "button9" value = "9" class = "numBtn">9</button>
<button id = "mulBtn" value = "*" class = "opBtn">*</button>
<br/>
<br/>
<button id = "clearBtn" value = "c">C</button>
<button id = "button0" value = "0" class = "numBtn">0</button>
<button id = "buttondot" value = "." class = numBtn >.</button>
<button id = "divBtn" value = "/" class = "opBtn">/</button>
<button id = "eqlBtn" value = "=" class = "opBtn">=</button>

<br />
<br />

app/views/currency/index.html.erb
<h1>Currency#index</h1>
<p>Find me in app/views/currency/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitcoin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/message/error.html.erb
<%= link_to image_tag("error.png", alt: "Rails"), '#' %>
<br />

app/views/message/index.html.erb
<%= link_to image_tag("success.png", alt: "Rails"), '#' %>
<br />

app/views/message/success.html.erb
<%= link_to image_tag("success.png", alt: "Rails"), '#' %>
<br />

app/views/message/test.html.erb
<%= @out %>
<br />
<br />
<br />
<%= @in %>

app/views/qrcode/index.html.erb
<h1>Please Scan The Qrcode</h1>
<h1>Money:<%= @amount%><%= @currency %></h1>
<h1>Bitcoin:<%= @bitcoin%> BTC</h1>
<h1>Rate:<%= @rate%></h1>
<style type="text/css">
 table {
   border-width: 0;
   border-style: none;
   border-color: #0000ff;
   border-collapse: collapse;
 }
 td {
   border-width: 0;
   border-style: none;
   border-color: #0000ff;
   border-collapse: collapse;
   padding: 0;
   margin: 0;
   width: 10px;
   height: 10px;
 }
 td.black { background-color: #000; }
 td.white { background-color: #fff; }
</style>
<table>
 <% @qr.modules.each_index do |x| %>
   <tr>
     <% @qr.modules.each_index do |y| %>
       <% if @qr.dark?(x,y) %>
         <td class="black"/>
       <% else %>
         <td class="white"/>
       <% end %>
     <% end %>
   </tr>
 <% end %>
</table>

<script>
$(document).ready(function() {
  var money = $("#money").val();
  var address = $("#address").val();
  var getData = {"money" : money , "address" : address};
  var url = "/message/index.json";
  var time = 10;
  var getTransInterval;
  var countDownInterval;

function GetTransactionRes(){
  $.get(url, getData , function(data) {
    if(data["status"] == "success"){
      endInterval();
      location.href = "/message/success";
    }
  });

    if(time <= 0){
      endInterval();
      location.href = "/message/error";
    }
  }

  function countDown(){
    $("#pad").html(time);
    time -= 1;
  }

  function endInterval(){
    clearInterval(getTransInterval);
    clearInterval(countDownInterval);
  }

  getTransInterval = setInterval(GetTransactionRes , 2000);
  countDownInterval = setInterval(countDown , 1000);
  
  });


</script>


<h1>
left:<span id="pad"></span>
<%= text_field_tag :money , @bitcoin , :type => :hidden  %>
<%= text_field_tag :address , @address , :type => :hidden %>
<!--input type="hidden" id="tx1" value= {{@}}>
<input type="hidden" id="tx2" value= '1KeHqnJbKQvTTjyTyakix1RJ9YGFphMwe6'--> 
</h1>

app/views/qrcode/show.html.erb
<h1>Qrcode#show</h1>
<p>Find me in app/views/qrcode/show.html.erb</p>

app/views/signup/index.html.erb
<h1>Sign Up</h1>
<%= form_tag signup_show_path, method: :post do %>
	<%= label_tag('Email') %>
	<%= text_field_tag :email, params[:email] %>
    <br />
    <br />
	<%= label_tag('Password') %>
	<%= text_field_tag :password, params[:password] %>
    <br />
    <br />
    <%= label_tag('Confirm Password') %>
	<%= text_field_tag :confirm_password, params[:confirm_password] %>
    <br />
    <br />
	<%= submit_tag "Sign Up" %>
<% end %>

app/views/signup/show.html.erb
<p>please check your email</p> 
<h1><%= @email%></h1>
<html>
<SCRIPT language="javascript"> 
var spantime = 10;
var endflag = false;
function cal()
{
    if (spantime == 0)
    { 
        window.location.href= '/';
    }
    else
    {
        spantime --;
        str = spantime + "s";
        document.getElementById("pad").innerHTML = str;
    }
}
window.onload = function()
{
    setInterval(cal, 1000);
}
</SCRIPT>  
</head>
<h1>
left:<span id="pad"></span>
</h1>
</html>